#!/bin/sh -e

export XDG_RUNTIME_DIR=$AUTOPKGTEST_TMP/runtime
export HOME=$AUTOPKGTEST_TMP/home
mkdir -p $XDG_RUNTIME_DIR $HOME
chmod 0700 $XDG_RUNTIME_DIR

DEBIAN_DIR=$(pwd)/debian

for py in $(py3versions -s)
do
    cd "$AUTOPKGTEST_TMP"
    echo "Testing with $py"
    $DEBIAN_DIR/run-tests $DEBIAN_DIR/get-test-exclusions autopkgtest $py \
      -m pytest $PYTEST_OPTIONS --pyargs notebook
done
